### ISSUE TITLE
sudo: ./piquadcopter.sh: command not found

### ISSUE THREAD

**Issue by Boxroma** [rgw3d/PiQuadcopter#1]
i have followed your instructions to the dot but i seem to always hit this error when i want to start the server "sudo: ./piquadcopter.sh: command not found" when ever i try to start this in the terminal help please..

**Comment by rgw3d** [comment]
Make sure that you are in the correct directory when you call ./piquadcopter.sh

From the command line, type 'ls' to display all of your files. If you do not see all of the files listed [here](https://github.com/rgw3d/PiQuadcopter), then you are in the wrong directory. 

Make sure that you are in the directory that you cloned  the PiQuadcopter repository into

If you still cannot run it, provide screenshots of your terminal window, with the output of the 'ls' command

**Comment by Boxroma** [comment]
sorry for the late reply..

so i cant currently take screen shots on the pi but i copied the whole terminal output and this is what it looks lilke 

<pi@raspberrypi:~ $ cd/home/
bash: cd/home/: No such file or directory
pi@raspberrypi:~ $ cd /home/pi
pi@raspberrypi:~ $ ls
Desktop     interfaces                  Music         Public
dhcpd.conf  isc-dhcp-server             oldconffiles  python_games
Documents   mjpg-streamer-code-182      Pictures      Templates
Downloads   mjpg-streamer-code-182.zip  piquadcopter  Videos
pi@raspberrypi:~ $ cd piquadcopter
pi@raspberrypi:~/piquadcopter $ ./piquadcopter.sh
bash: ./piquadcopter.sh: No such file or directory
pi@raspberrypi:~/piquadcopter $ ls
configure_port.o  msp.o            setup                 websocket.cpp
LICENSE           piquadserver.sh  setup_pi_software.sh  websocket.o
Makefile          README.md        websocket
pi@raspberrypi:~/piquadcopter $ ./piquadcopter.sh
bash: ./piquadcopter.sh: No such file or directory
pi@raspberrypi:~/piquadcopter $ 


and second question am i supposed to be running the piquadserver.sh instead? cause that is starting the hotpot quite alrite but cant connect to the flight controller or the phone or maybe i am missing something

**Comment by robert-solomon12** [comment]
Hi there, is it not ./piquadserver.sh to run the server in order to listen for commands that is sent from the smartphone to the pi ?, correct me if i'm wrong because I'm working on this project also using the Pi3. :)

**Comment by rgw3d** [comment]
Yes! My mistake in typing it up.

**Comment by rgw3d** [comment]
I have updateded the README. Let me know if it is working!

**Comment by EazyRob97** [comment]
Hey, thanks for the reply, I'm having issues with programming it on startup
and i'm not sure that's its working right ... would you be able to give me
your contacts and perhaps guide me through it and we could discuss more of
the problem that I have then ? My Facebook is:
https://www.facebook.com/thatgentleguy or my Skype as well which is
robertboy82 if you do have skype.
So far I can make the connection from my smartphone to the Raspberry Pi and
the Inputs are displaying and writing on the MultiWii but I havent been
able to make it work on startup, I can only connect to the Raspberry Pi and
thats it, its not receiving the commands. I could only see the raspberry Pi
receiving the commands when I launched the "piquadserver.sh" manually in
the "PiQuadcopter" directory. I have a screenshot of the File Path that I
implemented to run on startup so I tested it out and the error its printing
is that "./websocket command not found"
My Project is due in 3 weeks and would like a helping hand if you dont mind.

**Comment by robert-solomon12** [comment]
---------- Forwarded message ----------
From: Rob Solo <robsolo76@gmail.com>
Date: Mon, Apr 9, 2018 at 12:24 PM
Subject: Re: [rgw3d/PiQuadcopter] sudo: ./piquadcopter.sh: command not
found (#1)
To: rgw3d/PiQuadcopter <
reply@reply.github.com
>


Hey, thanks for the reply, I'm having issues with programming it on startup
and i'm not sure that's its working right ... would you be able to give me
your contacts and perhaps guide me through it and we could discuss more of
the problem that I have then ? My Facebook is:  https://www.facebook.com/
thatgentleguy or my Skype as well which is robertboy82 if you do have skype.
So far I can make the connection from my smartphone to the Raspberry Pi and
the Inputs are displaying and writing on the MultiWii but I havent been
able to make it work on startup, I can only connect to the Raspberry Pi and
thats it, its not receiving the commands. I could only see the raspberry Pi
receiving the commands when I launched the "piquadserver.sh" manually in
the "PiQuadcopter" directory. I have a screenshot of the File Path that I
implemented to run on startup so I tested it out and the error its printing
is that "./websocket command not found"
My Project is due in 3 weeks and would like a helping hand if you dont mind.

**Comment by rgw3d** [comment]
Should be resolved now, check the README. I also sent you an email.
