### ISSUE TITLE
Start up automatically on boot

### ISSUE THREAD

**Issue by naswanziq** [rgw3d/PiQuadcopter#2]
"To schedule everything to start up automatically on boot, edit /etc/rc.local with something like... /home/path/to/piquadcopter.sh."

How do i go about doing this? "cd /etc/rc.local"  will result in no such file or directory.

Thank You

**Comment by rgw3d** [comment]
Depending on what version of Raspberry Pi you are using, it will vary, but all versions _should_ have something similar to rc.local. I suggest Googling it, with your RPi version
